#!/usr/bin/env zsh
#
if [ -z "$TMUX" ] && [ ${UID} != 0 ]
then
    tmux new-session -A -s main
fi

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme

# Path to your oh-my-zsh installation.
export ZSH="/Users/azhahes/.oh-my-zsh"

plugins=(vi-mode zsh-autosuggestions zsh-syntax-highlighting fzf zsh-interactive-cd)

source "$ZSH/oh-my-zsh.sh"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
source "$ZDOTDIR/aliases.zsh"
source "$ZDOTDIR/options.zsh"
source "$ZDOTDIR/functions.zsh"

eval "$(zoxide init zsh)"

# # Refrence:
# # https://gitlab.com/fazzi/dotfiles.git
